
apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'application'
apply plugin: 'jacoco'

mainClassName = 'magnus4j.Main'

version = "1.0"
description = "Chess libray for Java"

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

jar {
    manifest {
        attributes ('Main-Class': mainClassName )
    }
}

test {
    testLogging {
        events "passed", "skipped", "failed"
    }
}


jacoco {
    toolVersion = "0.8.8"
}


jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
        html.required = true
    }
}

dependencies {
    testCompile 'junit:junit:4.11'
}
